cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED SYNC OR NOT DEFINED WORK)
    message(FATAL_ERROR "Expected SYNC and WORK")
endif()
set(source "${WORK}/source")
set(destination "${WORK}/installed/assets")
file(MAKE_DIRECTORY "${source}/ui/icons/spell" "${WORK}/user")
file(WRITE "${source}/ui/icons/spell/icon.png" "icon fixture")
file(WRITE "${source}/ui/icons/spell/mask.png" "mask fixture")
file(WRITE "${WORK}/user/keep.txt" "user file")
function(sync_assets)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE=${source}" "-DDESTINATION=${destination}"
        "-DOUTPUT_ROOT=${WORK}/installed" -P "${SYNC}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()
sync_assets()
if(NOT EXISTS "${destination}/ui/icons/spell/icon.png" OR NOT EXISTS "${destination}/ui/icons/spell/mask.png")
    message(FATAL_ERROR "Icon bundle was not copied")
endif()
file(REMOVE "${source}/ui/icons/spell/mask.png")
file(WRITE "${destination}/ui/icons/spell/team-mask.png" "obsolete name")
sync_assets()
if(EXISTS "${destination}/ui/icons/spell/mask.png" OR EXISTS "${destination}/ui/icons/spell/team-mask.png")
    message(FATAL_ERROR "Removed masks remain active in the installed assets")
endif()
file(READ "${destination}/ui/icons/spell/icon.png" icon)
if(NOT icon STREQUAL "icon fixture" OR NOT EXISTS "${WORK}/user/keep.txt")
    message(FATAL_ERROR "Asset sync touched unrelated content")
endif()
file(WRITE "${source}/ui/icons/spell/mask.png" "replacement mask")
sync_assets()
file(READ "${destination}/ui/icons/spell/mask.png" mask)
if(NOT mask STREQUAL "replacement mask")
    message(FATAL_ERROR "Added mask was not installed")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE=${source}" "-DDESTINATION=${WORK}/assets"
    "-DOUTPUT_ROOT=${WORK}/installed" -P "${SYNC}" RESULT_VARIABLE outsideResult OUTPUT_QUIET ERROR_QUIET)
if(outsideResult EQUAL 0)
    message(FATAL_ERROR "Asset sync allowed writes outside the output root")
endif()
