# Mirror source assets into a generated assets directory, including file removals.
# Otherwise removing an optional mask in the source leaves it active in an old build.
cmake_minimum_required(VERSION 3.25)
foreach(argument IN ITEMS SOURCE DESTINATION OUTPUT_ROOT)
    if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        message(FATAL_ERROR "Asset sync requires ${argument}")
    endif()
    file(REAL_PATH "${${argument}}" ${argument})
endforeach()
if(NOT IS_DIRECTORY "${SOURCE}")
    message(FATAL_ERROR "Missing source assets: ${SOURCE}")
endif()
cmake_path(IS_PREFIX OUTPUT_ROOT "${DESTINATION}" NORMALIZE insideOutput)
cmake_path(IS_PREFIX SOURCE "${DESTINATION}" NORMALIZE destinationInSource)
cmake_path(IS_PREFIX DESTINATION "${SOURCE}" NORMALIZE sourceInDestination)
cmake_path(GET DESTINATION FILENAME destinationName)
if(NOT insideOutput OR NOT destinationName STREQUAL "assets" OR destinationInSource OR sourceInDestination)
    message(FATAL_ERROR "Asset sync destination must be a separate generated assets directory: ${DESTINATION}")
endif()
file(GLOB_RECURSE installedEntries LIST_DIRECTORIES true "${DESTINATION}/*")
foreach(entry IN LISTS installedEntries)
    file(REAL_PATH "${entry}" resolved)
    cmake_path(IS_PREFIX DESTINATION "${resolved}" NORMALIZE insideDestination)
    if(IS_SYMLINK "${entry}" OR NOT insideDestination)
        message(FATAL_ERROR "Asset sync refuses redirected output: ${entry}")
    endif()
endforeach()
file(COPY "${SOURCE}/" DESTINATION "${DESTINATION}")
file(GLOB_RECURSE installedFiles LIST_DIRECTORIES false RELATIVE "${DESTINATION}" "${DESTINATION}/*")
foreach(relative IN LISTS installedFiles)
    if(NOT EXISTS "${SOURCE}/${relative}")
        file(REMOVE "${DESTINATION}/${relative}")
    endif()
endforeach()
